-- Enable the Vault extension
CREATE EXTENSION IF NOT EXISTS supabase_vault CASCADE;

-- ==========================================
-- Example: Encrypting Patient Medical Notes
-- ==========================================

-- 1. Create a Key ID (in production, use Supabase UI or pgsodium to generate a specific key)
-- We use a default key generated by vault for this example.

-- 2. Modify the Prescriptions table to use Vault for sensitive data (like diagnostic notes or exact medications)
-- Instead of a regular TEXT field, we will store a UUID reference to a Vault secret.

ALTER TABLE prescriptions ADD COLUMN secure_notes_id UUID;

-- Helper Function to securely insert/update prescriptions
-- This automatically encrypts the 'notes' text using Vault and stores the UUID reference
CREATE OR REPLACE FUNCTION insert_secure_prescription(
    p_tenant_id VARCHAR,
    p_appointment_id UUID,
    p_medications JSONB,
    p_sensitive_notes TEXT
) RETURNS UUID AS $$
DECLARE
    v_secret_id UUID;
    v_prescription_id UUID;
BEGIN
    -- Encrypt the sensitive notes and store in Vault
    -- vault.create_secret(secret text, name text, description text)
    SELECT vault.create_secret(
        p_sensitive_notes, 
        'prescription_notes_' || gen_random_uuid()::text,
        'Secure notes for appointment ' || p_appointment_id::text
    ) INTO v_secret_id;

    -- Insert the record with the Vault reference instead of raw text
    INSERT INTO prescriptions (tenant_id, appointment_id, medications, secure_notes_id)
    VALUES (p_tenant_id, p_appointment_id, p_medications, v_secret_id)
    RETURNING id INTO v_prescription_id;

    RETURN v_prescription_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. Create a Secure View for Server Actions
-- This view automatically joins the prescriptions table with vault.decrypted_secrets
-- so your backend can query it easily, while the physical disk only has encrypted data.
CREATE OR REPLACE VIEW secure_prescriptions_view AS
SELECT 
    p.id,
    p.tenant_id,
    p.appointment_id,
    p.medications,
    p.created_at,
    -- Decrypted data automatically fetched from Vault
    ds.decrypted_secret AS sensitive_notes
FROM prescriptions p
LEFT JOIN vault.decrypted_secrets ds ON p.secure_notes_id = ds.id;

-- Ensure RLS on the view or underlying tables applies properly
-- (When querying the view, postgres checks the underlying table's policies)
